import firstVideo from "./videos/firstVideo.mp4";
import secondVideo from "./videos/secondVideo.mp4";
import Video3 from "./videos/Video3.mp4";
import Video4 from "./videos/Video4.mp4";
import Video5 from "./videos/Video5.mp4";
import Video6 from "./videos/Video6.mp4";
import Video7 from "./videos/Video7.mp4";
import Video8 from "./videos/Video8.mp4";
import Video9 from "./videos/Video9.mp4";
import Video10 from "./videos/Video10.mp4";
import Video11 from "./videos/Video11.mp4";
import Video12 from "./videos/Video12.mp4";
import Video13 from "./videos/Video13.mp4";
import Video14 from "./videos/Video14.mp4";
import Video15 from "./videos/Video15.mp4";
import Video16 from "./videos/Video16.mp4";
import Video17 from "./videos/Video17.mp4";
import Video18 from "./videos/Video18.mp4";
const videos = { firstVideo, secondVideo, Video3, Video4, Video5, Video6, Video7, Video8, Video9, Video10, Video11, Video12, Video13, Video14, Video15, Video16, Video17, Video18 };
export default videos;
